common/templates: add templates to pin and unpin messages
botlabs-gg/yagpdb pull request #1065
Opened 2021-11-15 09:08 UTC by LemmeCry

Being able to pin/unpin messages with the bot has been a common request. This PR does just that by adding custom command templates which allow pinning/unpinning a message.
The syntax for the template usage will be:
- `pinMessage channel messageID`
- `unpinMessage channel messageID`

2021-11-15 10:17 UTC, LemmeCry commented
Those errors are handled automatically. Here is the error returned when you try to pin after the limit:
![image](https://user-images.githubusercontent.com/67655446/141764194-01566f09-d468-4d3d-8b15-4de22ac224c8.png)

2021-11-15 10:22 UTC, Wolveric commented
Yeah, that's the case I mean. Because it's difficult to track that count, I'd rather it not automatically panic because of that. I'd prefer the option to gracefully handle the error, by checking the return, indicating whether it failed.

2021-11-15 16:00 UTC, jo3-l commented on common/templates/context_funcs.go
> +func (c *Context) tmplHandlePinMessage(mode bool) func(channel, msgID interface{}) (string, error) {
```suggestion
func (c *Context) tmplPinMessage(mode bool) func(channel, msgID interface{}) (string, error) {
```
For consistency with similar higher-order functions.

2021-11-28 00:41 UTC, jo3-l requested changes

2021-11-28 00:41 UTC, jo3-l commented on common/templates/context.go
> +	c.addContextFunc("pinMessage", c.tmplPinMessage(true))
The values are 
```suggestion
	c.addContextFunc("pinMessage", c.tmplPinMessage(false))
```

The parameter specifies whether it should unpin.

2021-11-28 00:41 UTC, jo3-l commented on common/templates/context.go
> +	c.addContextFunc("unpinMessage", c.tmplPinMessage(false))
```suggestion
	c.addContextFunc("unpinMessage", c.tmplPinMessage(true))
```
Ditto.

2021-12-22 07:41 UTC, merged