add dadjoke command.
botlabs-gg/yagpdb pull request #1187
Opened 2022-04-23 21:20 UTC by savage4618

This command uses an API (icanhazdadjoke) to pull in a random dadjoke. 

I had contacted the original creator of this code to get it re-done. They had confirmed to me it still worked and they used it on their self-host. I have tested the code on my own self-host now.

2022-04-23 21:48 UTC, mrbentarikau requested changes
Header,Set takes only two string arguments, this will error out on compile

2022-04-23 23:03 UTC, jo3-l reviewed
Some overarching suggestions:

- Run `gofmt` on this file.
- Many of the comments seem superfluous; consider removing.

2022-04-23 23:03 UTC, jo3-l commented on stdcommands/dadjoke/dadjoke.go
> +		apiResp, err := client.Do(req)
```suggestion
		apiResp, err := http.DefaultClient.Do(req)
```

2022-04-23 23:03 UTC, jo3-l commented on stdcommands/dadjoke/dadjoke.go
> +		bytes, err := ioutil.ReadAll(apiResp.Body)
Package ioutil is deprecated. Use `io.ReadAll` instead.

2022-04-23 23:03 UTC, jo3-l commented on stdcommands/dadjoke/dadjoke.go
> +		joke1 := Joke{}
```suggestion
		var joke Joke
```

2022-04-23 23:03 UTC, jo3-l commented on stdcommands/dadjoke/dadjoke.go
> +		jsonErr := json.Unmarshal(bytes,&joke1)
```suggestion
		err = json.Unmarshal(bytes,&joke1)
```

2022-04-23 23:03 UTC, jo3-l commented on stdcommands/dadjoke/dadjoke.go
> +		}
```suggestion
		if err != nil {
			return nil, err
		}
```

2022-04-23 23:03 UTC, jo3-l commented on stdcommands/dadjoke/dadjoke.go
> +		return resp , nil
```suggestion
		return joke.Joke, nil
```

2022-04-27 23:49 UTC, savage4618 commented
Thank you Joe for reviewing. I fixed all suggested lines and tested with success.

2022-05-02 08:22 UTC, merged