Added exchange.go
botlabs-gg/yagpdb pull request #1349
Opened 2022-09-18 15:16 UTC by issacboil

This command was made by Shadow and Mr. Ben, but shadow doesn't know how to use git, so I am pull requesting it for him. 

Co-Authored-By: Shadow <66721908+Shadow21AR@users.noreply.github.com>

2022-09-21 15:34 UTC, mrbentarikau requested changes

2022-09-21 15:34 UTC, mrbentarikau commented on stdcommands/exchange/exchange.go
> +	Name:                "exchange",
Command name shoult start with capital letter.

2022-09-21 15:34 UTC, mrbentarikau commented on stdcommands/exchange/exchange.go
> +			Title:       "💱Currency Exhange Rate",
Typo

2022-09-23 22:19 UTC, ashishjh-bst commented
Please add screenshots of sample command usage.

2022-09-26 12:31 UTC, issacboil commented
![image](https://user-images.githubusercontent.com/40278713/192276586-292e2cbf-ee5f-44be-9c46-abd710dc2070.png)`

Here is a picture of the command usage.

2022-09-26 14:15 UTC, ashishjh-bst commented on stdcommands/exchange/exchange.go
> +            Timestamp:   time.Now().UTC().Format(time.RFC3339),
formatting

2022-09-26 14:15 UTC, ashishjh-bst commented on stdcommands/exchange/exchange.go
> +type SymbolInfo struct {
Change name to CurrencySymbolInfo?

2022-10-06 12:09 UTC, merged