Config page links
botlabs-gg/yagpdb pull request #1364
Opened 2022-11-06 23:34 UTC by Wolveric

Updating the rep and tickets system with links to their config pages in the control panel, when they error out because the system is disabled.

2022-11-07 00:05 UTC, jo3-l commented on reputation/plugin_bot.go
> +func repDisabledError(guild *dcmd.GuildContextData) string {
Perhaps rename this to `createRepDisabledError`?

2022-11-07 00:05 UTC, jo3-l commented on tickets/tickets_commands.go
> +func TicketsDisabledError(guild *dcmd.GuildContextData) string {
This probably shouldn't be exported. Also, consider renaming this to `createTicketsDisabledError`, similar to above.

2022-11-07 00:19 UTC, jo3-l commented
You renamed the functions, but not any of the references. I suggest that at the very least you use an editor/IDE with Go support so these issues are caught before committing.

2022-11-09 18:26 UTC, ashishjh-bst requested changes

2022-11-09 18:26 UTC, ashishjh-bst commented on reputation/plugin_bot.go
> +	return fmt.Sprintf("**The reputation system is disabled for this server.** Enable it at: <https://yagpdb.xyz/manage/%d/reputation>.", guild.GS.ID)
instead of using https://yagpdb.xyz, use `web.BaseURL()`

2022-11-09 18:26 UTC, ashishjh-bst commented on tickets/tickets_commands.go
> +	return fmt.Sprintf("**The tickets system is disabled for this server.** Enable it at: <https://yagpdb.xyz/manage/%d/tickets/settings>.", guild.GS.ID)
instead of using https://yagpdb.xyz/, use `web.BaseURL()`

2022-11-09 18:51 UTC, merged