fix: Empty Embed Error
botlabs-gg/yagpdb pull request #874
Opened 2021-04-25 01:00 UTC by devnote-dev

Due to a change with Discord Embeds, empty embeds can no longer be created and an empty description field is no longer accepted. This means that currently the `simpleembed` and `customembed` commands throw the following error when no description is provided: `HTTP 400 Bad Request, {"embed": ["description"]}`. This PR fixes this, as well as three additional bugs with the commands:
- URL field not included if no Title is provided
- Author field not included if no name is provided
- Footer field not included if no text is provided

I'm no expert with Golang so additional reviews/testing is requested please, thanks!

2021-04-27 18:18 UTC, jonas747 commented
sending "\u200b" is a bit too hacky IMO, we should instead error out with a more helpfull message

2021-04-28 19:03 UTC, devnote-dev commented
ZWS for description has been removed 👍

2021-04-28 19:44 UTC, jonas747 commented
Embeds are valid without a description if you provide a title for example

2021-04-29 20:51 UTC, devnote-dev commented
Ah my bad, latest commits should now check for required/non-required fields now before sending

2021-05-01 22:46 UTC, jonas747 requested changes
Im a bit puzzled by the neted if statements

2021-05-01 22:46 UTC, jonas747 commented on stdcommands/simpleembed/simpleembed.go
> +    			if data.Switch("title").Str() == "" &&
I don't quite understand why the parent if statement needs to exist

2021-05-01 22:46 UTC, jonas747 commented on stdcommands/simpleembed/simpleembed.go
> +		&dcmd.ArgDef{Switch: "author", Help: "The text in the 'author' field", Type: dcmd.String, Default: "\u200b"},
u200b is still present in the defaults

2022-04-11 09:44 UTC, ashishjh-bst commented
review comments from jonas are still not resolved, plus the branch needs to be rebased.

2022-04-11 10:20 UTC, devnote-dev commented
I will reopen this when I have time and a working testing environment (or someone else can fix this).

2022-04-11 10:20 UTC, closed without merging