stdcommands: Add songwhip command
botlabs-gg/yagpdb pull request #902
Opened 2021-05-07 21:17 UTC by l-zeuch

Songwhip is a small website hosted by a one-man army and provides a simple yet effective API.
We can make POST requests with the song URL as payload and receive a page back, listing all platforms which have that song.

I've seen that site used in a music-related Discord server, did a bit of research and found that they provide an API and ended up making a command for it.

Works fine on selfhost, as far as I can tell. Nifty screenshot:
![image](https://user-images.githubusercontent.com/71897876/117509104-f32b1780-af89-11eb-8c97-f6b4abcc39d1.png)

The cooldown might be debatable, but I wanted to be easy on the API.
Cheers!

2021-05-08 09:36 UTC, l-zeuch commented
A night later I'm not quite happy with the embed, if y'all have any input I'd appreciate it : )

2021-05-10 14:10 UTC, jonas747 requested changes
I don't see any reason why we can't enable slash commands on this command

2021-05-11 04:53 UTC, l-zeuch commented
Has a few conflicts now and I want to use more up-to-date methods, as ioutils is deprecated in Go 16. Converting to draft for now.

2021-05-11 16:08 UTC, l-zeuch commented
Should be ready now! 😄

2021-06-03 17:05 UTC, l-zeuch commented
Not sure why it redouts now... Investigating

2021-10-27 19:46 UTC, closed without merging